version: "3"
services:
    frontend:
        container_name: cfy_client
        build:
            context: ./client
            dockerfile: Dockerfile
        image: piupiu/cfy_client
        ports:
            - "3000:3000"
    backend:
        container_name: cfy_server
        build:
            context: ./server
            dockerfile: Dockerfile
        image: piupiu/cfy_server
        ports:
            - "5000:5000"

networks:
      default:
        name: appnetwork
          